{{- if empty .Values.integrations.axway.secretName | and .Values.integrations.axway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: resurface-axway-creds
type: Opaque
data:
  clientID: {{ .Values.integrations.axway.clientID | toString | b64enc }}
  clientSecret: {{ .Values.integrations.axway.clientSecret | toString | b64enc }}
  orgID: {{ .Values.integrations.axway.orgID | toString | b64enc }}
{{- end }}