{{- $tls := default "" .Values.provider | eq "ibm-openshift" | or .Values.ingress.tls.enabled | ternary ":ssl" "" -}}
{{- $iss := lookup "v1" "Secret" .Release.Namespace "trino-iss" -}}
{{- if empty $iss -}}
{{- $iss = randAscii 32 | b64enc -}}
{{- else -}}
{{ $iss = $iss.data.iss }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: trino-iss
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  iss: {{ $iss }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coordinator-config
  namespace: {{ .Release.Namespace }}
data:
  config.properties: |
    {{- include "resurface.config.coordinator" . | nindent 4 }}
    internal-communication.shared-secret={{ $iss }}
{{- if and .Values.auth.enabled .Values.auth.basic.enabled }}
  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=etc/creds/password.db
---
apiVersion: v1
kind: Secret
metadata:
  name: trino-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password.db: {{ include "resurface.auth.creds" . }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-worker-config
  namespace: {{ .Release.Namespace }}
data:
  config.properties: |
    {{- include "resurface.config.worker" . | nindent 4 }}
    internal-communication.shared-secret={{ $iss }}
{{- if default "" .Values.provider | ne "ibm-openshift" | and .Values.ingress.controller.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-errorfiles
data:
  503: |-
    HTTP/1.0 503 Service Unavailable
    Cache-Control: must-revalidate,no-cache,no-store
    Connection: close
    Content-Type: text/html;charset=utf-8

    <html>
      <title>503 Service Unavailable</title>
      <style>
        body { background-color: rgba(48,48,48); font-family: Arial, sans-serif; text-align: center; }
        div { color: white; margin-top:100px; font-size: 120%; }
        h1 { font-weight: 500; }
        p { color: rgba(230,230,230); }
        a { color: inherit; }
        #contact { margin-top: 25px; }
      </style>
      <body>
        <div>
          <h1>No available nodes 😮‍💨</h1>
          <p>
            Sorry, there are no Graylog API Security nodes available to handle your request just yet.
            Please, try again in a few minutes.
          </p>
          <p id="contact">
            If this issue persists, please contact support at <a href="mailto:api-support@graylog.com">api-support@graylog.com</a>.
          </p>
        <div>
      </body>
    </html>
{{- if and .Values.iceberg.enabled .Values.minio.enabled .Values.ingress.minio.expose }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-extra-ports
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.ingress.minio.port | default 9001 | int }}:
    {{ index .Subcharts "minio" | include "minio.fullname" | printf "%s/%[4]s-console:%[2]s%[3]s" .Release.Namespace .Values.minio.consoleService.port $tls }}
{{- end }}
{{- end }}