{{- if empty .Values.integrations.axway.secretName | and .Values.integrations.axway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: resurface-axway-creds
type: Opaque
data:
  clientID: {{ .Values.integrations.axway.clientID | toString | b64enc }}
  clientSecret: {{ .Values.integrations.axway.clientSecret | toString | b64enc }}
  orgID: {{ .Values.integrations.axway.orgID | toString | b64enc }}
{{- end }}
---
{{- if empty .Values.integrations.tyk.secretName | and .Values.integrations.tyk.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: resurface-tyk-gw-creds
type: Opaque
data:
  url: {{ .Values.integrations.tyk.url | toString | b64enc }}
  authSecret: {{ .Values.integrations.tyk.authSecret | toString | b64enc }}
{{- end }}
