apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resurface.fullname" . | printf "%s-sa" }}
  namespace: {{ .Release.Namespace }}
{{- if default "" .Values.provider | ne "ibm-openshift" | and .Values.ingress.controller.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resurface.fullname" . | printf "%s-patcher-sa" }}
  namespace: {{ .Release.Namespace }}
{{ end -}}
