apiVersion: v2
name: resurface
version: 3.8.0
type: application
description: Resurface discovers and alerts on quality and security signatures in your API traffic.
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Default StorageClass (gp2) for EKS >1.30
    - kind: added
      description: Self-signed certificate support for network sniffer
    - kind: added
      description: Promiscuous mode option for network sniffer
    - kind: changed
      description: Upgrade Resurface image to 3.6.116
    - kind: changed
      description: Upgrade Network Sniffer image to 1.5.1
    - kind: changed
      description: Upgrade HAProxy dependency chart to 1.39.4
    - kind: fixed
      description: Secure capture URL for network sniffer
    - kind: fixed
      description: SSL/TLS redirect port for HAProxy ingress
keywords:
  - API
  - HTTP
  - SOAP
  - REST
  - GraphQL
  - Triage
  - Security
  - Observability
  - Logs
  - Monitoring
  - Troubleshooting
  - Alerts
home: https://resurface.io
dependencies:
  - name: kubernetes-ingress
    version: "1.39.4"
    repository: https://haproxytech.github.io/helm-charts
    condition: ingress.controller.enabled
  - name: minio
    version: "5.2.0"
    repository: https://charts.min.io/
    condition: minio.enabled
maintainers:
  - name: Ramón Márquez
    email: ramon@resurface.io
  - name: Rob Dickinson
    email: rob@resurface.io
sources:
  - https://github.com/resurfaceio
icon: https://raw.githubusercontent.com/resurfaceio/insomnia-plugin/master/assets/plugin/icon-alt.svg
appVersion: 3.6.116
