apiVersion: v2
name: resurface
version: 3.8.1
type: application
description: Resurface discovers and alerts on quality and security signatures in your API traffic.
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: changed
      description: Upgrade azure-eh image to 1.1.1
    - kind: changed
      description: Logging rules now support HTTP traffic by default
    - kind: fixed
      description: Secure capture URL for event consumer apps
    - kind: fixed
      description: Tolerations required by GKE on ARM for event consumer apps
keywords:
  - API
  - HTTP
  - SOAP
  - REST
  - GraphQL
  - Triage
  - Security
  - Observability
  - Logs
  - Monitoring
  - Troubleshooting
  - Alerts
home: https://resurface.io
dependencies:
  - name: kubernetes-ingress
    version: "1.39.4"
    repository: https://haproxytech.github.io/helm-charts
    condition: ingress.controller.enabled
  - name: minio
    version: "5.2.0"
    repository: https://charts.min.io/
    condition: minio.enabled
maintainers:
  - name: Ramón Márquez
    email: ramon@resurface.io
  - name: Rob Dickinson
    email: rob@resurface.io
sources:
  - https://github.com/resurfaceio
icon: https://raw.githubusercontent.com/resurfaceio/insomnia-plugin/master/assets/plugin/icon-alt.svg
appVersion: 3.6.116
