# Default values for Resurface
# This is a YAML-formatted file.

provider:
units: binary

ingress:
  enabled: true
  controller:
    enabled: true
  importer:
    expose: true
    path: "/fluke"
  minio:
    expose: false
    port: 9001
  tls:
    enabled: false
    host: 
    autoissue:
      enabled: true
      staging: true
      email: 
    byoc:
      secretname:
      cert:
      key:

auth:
  enabled: false
  basic:
    enabled: false
    credentials:
      - username: 
        password: 
  jwt:
    enabled: false
    jwksurl: 
  oauth2:
    enabled: false
    issuer: 
    authurl: 
    tokenurl: 
    jwksurl: 
    userinfourl: 
    clientid: 
    clientsecret: 

multinode:
  enabled: false
  workers: 1

iceberg:
  enabled: false
  s3:
    enabled: false
    bucketname:
    aws:
      region:
      accesskey:
      secretkey:
  config:
    format: PARQUET
    codec: ZSTD
    shards: 4
    millis: 20000
    size:
      max: 100
      reserved: 20

integrations:
  axway:
    enabled: false
    secretName:
    clientID:
    clientSecret:
    orgID:
  tyk:
    enabled: false
    secretName:
    url:
    authSecret:

custom:
  service:
    apiexplorer:
      port:
      type:
    flukeserver:
      port:
      type:
  resources:
    cpu:
    memory:
  config:
    dbsize:
    dbheap:
    dbslabs:
    shardsize:
    pollingcycle:
    tz:
    version:
    writerequestbodies:
    writerequestheaders:
    writeresponsebodies:
    writeresponseheaders:
    writepiitokens:
    skippii:
  storage:
    size:
    classname:

sniffer:
  enabled: false
  discovery:
    enabled: false
    skip:
      ns: [ "kube-system" ]
      svc: [ "kubernetes" ]
  services:
  pods:
  labels:
  promisc:
    enabled: false
  vpcmirror:
    enabled: false
    ports:
    vnis:
    autosetup:
      enabled: false
      schedule: "0 * * * *"
      source:
        ecs:
          clusters:
        ec2:
          instances:
          autoscaling:
      target:
        eks:
          cluster:
          nodegroup:
        sg:
        id:
      filter:
        id:
  logger:
    enabled: true
    rules: |
      include debug
      skip_compression

consumer:
  azure:
    enabled: false
    verbose: false
    ehname: apimlogs
    storagecontainername: 
    ehconnstring: 
    storageconnstring: 
  aws:
    enabled: false
    kdsname: 
    region: 
    accesskeyid: 
    accesskeysecret: 
    accesskey:
      enabled:
  logger:
    enabled: true
    bypass: false
    rules: |
      include debug

# Base tolerations
tolerations: &base_tolerations
  - key: kubernetes.io/arch
    operator: Equal
    value: arm64
    effect: NoSchedule

# Dependency chart: HAProxy Ingress Controller
kubernetes-ingress:
  controller:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      enablePorts:
        stat: false
        quic: false
        prometheus: false
      tcpPorts:
        - name: minioc
          port: 9001
          targetPort: 9001
    extraArgs:
      - "--configmap-tcp-services=resurface/haproxy-extra-ports"
      - "--configmap-errorfiles=resurface/haproxy-errorfiles"
    tolerations: *base_tolerations

# Dependency chart: MinIO Object Storage
minio:
  enabled: false
  rootUser:
  rootPassword:
  mode: standalone
  replicas: 1
  persistence:
    size: 100Gi
  resources:
    requests:
      memory: 4Gi
  buckets:
    - name: iceberg.resurface
  serviceAccount:
    name: "minio-sa"
  configPathmc: "/tmp/minio/mc/"
  tolerations: *base_tolerations
  postJob:
    tolerations: *base_tolerations

qa:
  enabled: false
  simulator:
    enabled: false
    version:
    workload:
    host:
    port:
    limit:
      messages:
      millis:
    sleep:
      init:
      batch:
    clockskew:
    batchsize:
  importer:

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   targetMemoryUtilizationPercentage: 80
#544100452964.dkr.ecr.us-west-2.amazonaws.com